In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [102]:
df=pd.read_csv('income_evaluation.csv')
df

age          workclass   fnlwgt    education   education-num  \
0       39          State-gov    77516    Bachelors              13   
1       50   Self-emp-not-inc    83311    Bachelors              13   
2       38            Private   215646      HS-grad               9   
3       53            Private   234721         11th               7   
4       28            Private   338409    Bachelors              13   
...    ...                ...      ...          ...             ...   
32556   27            Private   257302   Assoc-acdm              12   
32557   40            Private   154374      HS-grad               9   
32558   58            Private   151910      HS-grad               9   
32559   22            Private   201490      HS-grad               9   
32560   52       Self-emp-inc   287927      HS-grad               9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex   capital-gain   capital-loss   hours-per-week  native-country  \
0         Male           2174              0               40   United-States   
1         Male              0              0               13   United-States   
2         Male              0              0               40   United-States   
3         Male              0              0               40   United-States   
4       Female              0              0               40            Cuba   
...        ...            ...            ...              ...             ...   
32556   Female              0              0               38   United-States   
32557     Male              0              0               40   United-States   
32558   Female              0              0               40   United-States   
32559     Male              0              0               20   United-States   
32560   Female          15024              0               40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [103]:
df.columns

Index(['age', ' workclass', ' fnlwgt', ' education', ' education-num',
       ' marital-status', ' occupation', ' relationship', ' race', ' sex',
       ' capital-gain', ' capital-loss', ' hours-per-week', ' native-country',
       ' income'],
      dtype='object')

In [117]:
df.columns = [col if i == 0 else col.replace(' ', '') for i, col in enumerate(df.columns)]

In [118]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [159]:
y = df['income']
x = df.drop('income', axis = 1)

In [160]:
y

0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
          ...  
32556     <=50K
32557      >50K
32558     <=50K
32559     <=50K
32560      >50K
Name: income, Length: 32561, dtype: object

In [161]:
#y_final = y.apply(lambda x: 1 if x=='>50K' else 0)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

y_final = label_encoder.fit_transform(y)

In [162]:
y_final

array([0, 0, 0, ..., 0, 0, 1])

In [163]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

numerical = ['age', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
x[numerical] = scaler.fit_transform(x[numerical])
x

age          workclass  fnlwgt    education  education-num  \
0      0.301370          State-gov   77516    Bachelors       0.800000   
1      0.452055   Self-emp-not-inc   83311    Bachelors       0.800000   
2      0.287671            Private  215646      HS-grad       0.533333   
3      0.493151            Private  234721         11th       0.400000   
4      0.150685            Private  338409    Bachelors       0.800000   
...         ...                ...     ...          ...            ...   
32556  0.136986            Private  257302   Assoc-acdm       0.733333   
32557  0.315068            Private  154374      HS-grad       0.533333   
32558  0.561644            Private  151910      HS-grad       0.533333   
32559  0.068493            Private  201490      HS-grad       0.533333   
32560  0.479452       Self-emp-inc  287927      HS-grad       0.533333   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  
0         Male      0.021740           0.0        0.397959   United-States  
1         Male      0.000000           0.0        0.122449   United-States  
2         Male      0.000000           0.0        0.397959   United-States  
3         Male      0.000000           0.0        0.397959   United-States  
4       Female      0.000000           0.0        0.397959            Cuba  
...        ...           ...           ...             ...             ...  
32556   Female      0.000000           0.0        0.377551   United-States  
32557     Male      0.000000           0.0        0.397959   United-States  
32558   Female      0.000000           0.0        0.397959   United-States  
32559     Male      0.000000           0.0        0.193878   United-States  
32560   Female      0.150242           0.0        0.397959   United-States  

[32561 rows x 14 columns]

In [164]:
x_final = pd.get_dummies(x)

In [165]:
x_final

age  fnlwgt  education-num  capital-gain  capital-loss  \
0      0.301370   77516       0.800000      0.021740           0.0   
1      0.452055   83311       0.800000      0.000000           0.0   
2      0.287671  215646       0.533333      0.000000           0.0   
3      0.493151  234721       0.400000      0.000000           0.0   
4      0.150685  338409       0.800000      0.000000           0.0   
...         ...     ...            ...           ...           ...   
32556  0.136986  257302       0.733333      0.000000           0.0   
32557  0.315068  154374       0.533333      0.000000           0.0   
32558  0.561644  151910       0.533333      0.000000           0.0   
32559  0.068493  201490       0.533333      0.000000           0.0   
32560  0.479452  287927       0.533333      0.150242           0.0   

       hours-per-week  workclass_ ?  workclass_ Federal-gov  \
0            0.397959             0                       0   
1            0.122449             0                       0   
2            0.397959             0                       0   
3            0.397959             0                       0   
4            0.397959             0                       0   
...               ...           ...                     ...   
32556        0.377551             0                       0   
32557        0.397959             0                       0   
32558        0.397959             0                       0   
32559        0.193878             0                       0   
32560        0.397959             0                       0   

       workclass_ Local-gov  workclass_ Never-worked  ...  \
0                         0                        0  ...   
1                         0                        0  ...   
2                         0                        0  ...   
3                         0                        0  ...   
4                         0                        0  ...   
...                     ...                      ...  ...   
32556                     0                        0  ...   
32557                     0                        0  ...   
32558                     0                        0  ...   
32559                     0                        0  ...   
32560                     0                        0  ...   

       native-country_ Portugal  native-country_ Puerto-Rico  \
0                             0                            0   
1                             0                            0   
2                             0                            0   
3                             0                            0   
4                             0                            0   
...                         ...                          ...   
32556                         0                            0   
32557                         0                            0   
32558                         0                            0   
32559                         0                            0   
32560                         0                            0   

       native-country_ Scotland  native-country_ South  \
0                             0                      0   
1                             0                      0   
2                             0                      0   
3                             0                      0   
4                             0                      0   
...                         ...                    ...   
32556                         0                      0   
32557                         0                      0   
32558                         0                      0   
32559                         0                      0   
32560                         0                      0   

       native-country_ Taiwan  native-country_ Thailand  \
0                           0                         0   
1                           0                         0   
2                           0         

In [166]:
from sklearn.model_selection import train_test_split

In [175]:
x_train,x_test,y_train,y_test = train_test_split(x_final, y_final, test_size = 0.25, random_state = 1)

In [176]:
from sklearn.ensemble import GradientBoostingClassifier
cls=GradientBoostingClassifier(n_estimators=500, learning_rate=0.05, random_state=0)

In [177]:
cls.fit(x_train,y_train)

GradientBoostingClassifier(learning_rate=0.05, n_estimators=500, random_state=0)

In [178]:
y_pred = cls.predict(x_test)

In [179]:
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [180]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy = accuracy_score(y_test,y_pred)

In [181]:
accuracy

0.8751996069278959

In [185]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.90      0.94      0.92      6303
           1       0.76      0.65      0.70      1838

    accuracy                           0.88      8141
   macro avg       0.83      0.80      0.81      8141
weighted avg       0.87      0.88      0.87      8141



In [186]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[5932,  371],
       [ 645, 1193]], dtype=int64)

In [187]:
from sklearn.model_selection import GridSearchCV
grid = {'learning_rate':[0.01,0.05,0.1], 'n_estimators':np.arange(100,500,100),}

In [188]:
gb_cv = GridSearchCV(cls, grid, cv = 4)
gb_cv.fit(x_train,y_train)

GridSearchCV(cv=4,
             estimator=GradientBoostingClassifier(learning_rate=0.05,
                                                  n_estimators=500,
                                                  random_state=0),
             param_grid={'learning_rate': [0.01, 0.05, 0.1],
                         'n_estimators': array([100, 200, 300, 400])})

In [189]:
print("Best Parameters:",gb_cv.best_params_)
print("Train Score:",gb_cv.best_score_)
print("Test Score:",gb_cv.score(x_test,y_test))

Best Parameters: {'learning_rate': 0.1, 'n_estimators': 400}
Train Score: 0.8712121212121212
Test Score: 0.8755681120255497


In [191]:
grid = {'learning_rate':[0.01,0.05,0.1], 'n_estimators':np.arange(100,500,100),'max_depth':[2,3,4,5,6,7] }

In [192]:
gb_cv = GridSearchCV(cls, grid, cv = 4)
gb_cv.fit(x_train,y_train)

GridSearchCV(cv=4,
             estimator=GradientBoostingClassifier(learning_rate=0.05,
                                                  n_estimators=500,
                                                  random_state=0),
             param_grid={'learning_rate': [0.01, 0.05, 0.1],
                         'max_depth': [2, 3, 4, 5, 6, 7],
                         'n_estimators': array([100, 200, 300, 400])})

In [193]:
print("Best Parameters:",gb_cv.best_params_)
print("Train Score:",gb_cv.best_score_)
print("Test Score:",gb_cv.score(x_test,y_test))

Best Parameters: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 400}
Train Score: 0.8712121212121212
Test Score: 0.8755681120255497
