In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_diabetes

In [4]:
diabetes=load_diabetes()
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [6]:
x=diabetes.data
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [7]:
y=diabetes.target
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=42)

In [10]:
from sklearn.ensemble import GradientBoostingRegressor
cls=GradientBoostingRegressor(n_estimators=500, learning_rate=0.05, random_state=0)

In [11]:
cls.fit(x_train,y_train)

GradientBoostingRegressor(learning_rate=0.05, n_estimators=500, random_state=0)

In [12]:
y_pred = cls.predict(x_test)

In [13]:
y_pred

array([171.64631987, 182.66453626, 182.2099014 , 262.61140949,
       122.42222454, 104.91439247, 268.50572225, 187.76464907,
       148.55894454, 157.00229544,  96.7716543 , 214.78843153,
        93.79027682, 240.78332864, 129.9247839 , 105.30832259,
       240.15959275, 258.17701508, 169.103919  , 235.10551188,
       184.2762683 , 102.46591212,  47.54629317, 210.48869916,
       154.19844908, 196.91068619, 226.11976574, 221.63943069,
        69.44387399, 113.85449948, 180.09614013, 134.23388409,
       152.77924988, 201.08909462, 126.95014556, 194.06420602,
        97.09892552, 107.70443695, 177.26453139,  71.30427292,
        78.61324755,  85.09645853, 204.92216619, 212.14897342,
       178.1456706 ,  72.93906402,  96.67117742, 126.81567982,
        62.80663461, 144.45861808, 101.55317597,  78.83506959,
       153.76959719, 106.03818299, 217.42979345, 136.37558393,
        93.46566567, 222.22455767, 100.76997124, 101.51221305,
       173.06741268, 185.98452361,  94.9155635 ,  75.89

In [16]:
from sklearn.metrics import r2_score,confusion_matrix
accuracy = r2_score(y_test,y_pred)

In [17]:
accuracy

0.4010240476851329

In [22]:
from sklearn.model_selection import GridSearchCV
grid = {'learning_rate':[0.01,0.05,0.1], 'n_estimators':np.arange(100,500,100),'max_depth':[2,3,4,5,6,7] }

In [23]:
gb_cv = GridSearchCV(cls, grid, cv = 4)
gb_cv.fit(x_train,y_train)

GridSearchCV(cv=4,
             estimator=GradientBoostingRegressor(learning_rate=0.05,
                                                 n_estimators=500,
                                                 random_state=0),
             param_grid={'learning_rate': [0.01, 0.05, 0.1],
                         'max_depth': [2, 3, 4, 5, 6, 7],
                         'n_estimators': array([100, 200, 300, 400])})

In [24]:
print("Best Parameters:",gb_cv.best_params_)
print("Train Score:",gb_cv.best_score_)
print("Test Score:",gb_cv.score(x_test,y_test))

Best Parameters: {'learning_rate': 0.01, 'max_depth': 2, 'n_estimators': 400}
Train Score: 0.3963117346321354
Test Score: 0.4751965382635749
